#pragma once

// From glfw3.h
#define BBZL_MOUSE_BUTTON_1 0
#define BBZL_MOUSE_BUTTON_2 1
#define BBZL_MOUSE_BUTTON_3 2
#define BBZL_MOUSE_BUTTON_4 3
#define BBZL_MOUSE_BUTTON_5 4
#define BBZL_MOUSE_BUTTON_6 5
#define BBZL_MOUSE_BUTTON_7 6
#define BBZL_MOUSE_BUTTON_8 7
#define BBZL_MOUSE_BUTTON_LAST BBZL_MOUSE_BUTTON_8
#define BBZL_MOUSE_BUTTON_LEFT BBZL_MOUSE_BUTTON_1
#define BBZL_MOUSE_BUTTON_RIGHT BBZL_MOUSE_BUTTON_2
#define BBZL_MOUSE_BUTTON_MIDDLE BBZL_MOUSE_BUTTON_3
