#pragma once

// From glfw3.h
#define BUBBLE_MOUSE_BUTTON_1         0
#define BUBBLE_MOUSE_BUTTON_2         1
#define BUBBLE_MOUSE_BUTTON_3         2
#define BUBBLE_MOUSE_BUTTON_4         3
#define BUBBLE_MOUSE_BUTTON_5         4
#define BUBBLE_MOUSE_BUTTON_6         5
#define BUBBLE_MOUSE_BUTTON_7         6
#define BUBBLE_MOUSE_BUTTON_8         7
#define BUBBLE_MOUSE_BUTTON_LAST      BUBBLE_MOUSE_BUTTON_8
#define BUBBLE_MOUSE_BUTTON_LEFT      BUBBLE_MOUSE_BUTTON_1
#define BUBBLE_MOUSE_BUTTON_RIGHT     BUBBLE_MOUSE_BUTTON_2
#define BUBBLE_MOUSE_BUTTON_MIDDLE    BUBBLE_MOUSE_BUTTON_3