#pragma once

// From glfw3.h
#define BUTTERFLY_KEY_SPACE 32
#define BUTTERFLY_KEY_APOSTROPHE 39 /* ' */
#define BUTTERFLY_KEY_COMMA 44      /* , */
#define BUTTERFLY_KEY_MINUS 45      /* - */
#define BUTTERFLY_KEY_PERIOD 46     /* . */
#define BUTTERFLY_KEY_SLASH 47      /* / */
#define BUTTERFLY_KEY_0 48
#define BUTTERFLY_KEY_1 49
#define BUTTERFLY_KEY_2 50
#define BUTTERFLY_KEY_3 51
#define BUTTERFLY_KEY_4 52
#define BUTTERFLY_KEY_5 53
#define BUTTERFLY_KEY_6 54
#define BUTTERFLY_KEY_7 55
#define BUTTERFLY_KEY_8 56
#define BUTTERFLY_KEY_9 57
#define BUTTERFLY_KEY_SEMICOLON 59 /* ; */
#define BUTTERFLY_KEY_EQUAL 61     /* = */
#define BUTTERFLY_KEY_A 65
#define BUTTERFLY_KEY_B 66
#define BUTTERFLY_KEY_C 67
#define BUTTERFLY_KEY_D 68
#define BUTTERFLY_KEY_E 69
#define BUTTERFLY_KEY_F 70
#define BUTTERFLY_KEY_G 71
#define BUTTERFLY_KEY_H 72
#define BUTTERFLY_KEY_I 73
#define BUTTERFLY_KEY_J 74
#define BUTTERFLY_KEY_K 75
#define BUTTERFLY_KEY_L 76
#define BUTTERFLY_KEY_M 77
#define BUTTERFLY_KEY_N 78
#define BUTTERFLY_KEY_O 79
#define BUTTERFLY_KEY_P 80
#define BUTTERFLY_KEY_Q 81
#define BUTTERFLY_KEY_R 82
#define BUTTERFLY_KEY_S 83
#define BUTTERFLY_KEY_T 84
#define BUTTERFLY_KEY_U 85
#define BUTTERFLY_KEY_V 86
#define BUTTERFLY_KEY_W 87
#define BUTTERFLY_KEY_X 88
#define BUTTERFLY_KEY_Y 89
#define BUTTERFLY_KEY_Z 90
#define BUTTERFLY_KEY_LEFT_BRACKET 91  /* [ */
#define BUTTERFLY_KEY_BACKSLASH 92     /* \ */
#define BUTTERFLY_KEY_RIGHT_BRACKET 93 /* ] */
#define BUTTERFLY_KEY_GRAVE_ACCENT 96  /* ` */
#define BUTTERFLY_KEY_WORLD_1 161      /* non-US #1 */
#define BUTTERFLY_KEY_WORLD_2 162      /* non-US #2 */

/* Function keys */
#define BUTTERFLY_KEY_ESCAPE 256
#define BUTTERFLY_KEY_ENTER 257
#define BUTTERFLY_KEY_TAB 258
#define BUTTERFLY_KEY_BACKSPACE 259
#define BUTTERFLY_KEY_INSERT 260
#define BUTTERFLY_KEY_DELETE 261
#define BUTTERFLY_KEY_RIGHT 262
#define BUTTERFLY_KEY_LEFT 263
#define BUTTERFLY_KEY_DOWN 264
#define BUTTERFLY_KEY_UP 265
#define BUTTERFLY_KEY_PAGE_UP 266
#define BUTTERFLY_KEY_PAGE_DOWN 267
#define BUTTERFLY_KEY_HOME 268
#define BUTTERFLY_KEY_END 269
#define BUTTERFLY_KEY_CAPS_LOCK 280
#define BUTTERFLY_KEY_SCROLL_LOCK 281
#define BUTTERFLY_KEY_NUM_LOCK 282
#define BUTTERFLY_KEY_PRINT_SCREEN 283
#define BUTTERFLY_KEY_PAUSE 284
#define BUTTERFLY_KEY_F1 290
#define BUTTERFLY_KEY_F2 291
#define BUTTERFLY_KEY_F3 292
#define BUTTERFLY_KEY_F4 293
#define BUTTERFLY_KEY_F5 294
#define BUTTERFLY_KEY_F6 295
#define BUTTERFLY_KEY_F7 296
#define BUTTERFLY_KEY_F8 297
#define BUTTERFLY_KEY_F9 298
#define BUTTERFLY_KEY_F10 299
#define BUTTERFLY_KEY_F11 300
#define BUTTERFLY_KEY_F12 301
#define BUTTERFLY_KEY_F13 302
#define BUTTERFLY_KEY_F14 303
#define BUTTERFLY_KEY_F15 304
#define BUTTERFLY_KEY_F16 305
#define BUTTERFLY_KEY_F17 306
#define BUTTERFLY_KEY_F18 307
#define BUTTERFLY_KEY_F19 308
#define BUTTERFLY_KEY_F20 309
#define BUTTERFLY_KEY_F21 310
#define BUTTERFLY_KEY_F22 311
#define BUTTERFLY_KEY_F23 312
#define BUTTERFLY_KEY_F24 313
#define BUTTERFLY_KEY_F25 314
#define BUTTERFLY_KEY_KP_0 320
#define BUTTERFLY_KEY_KP_1 321
#define BUTTERFLY_KEY_KP_2 322
#define BUTTERFLY_KEY_KP_3 323
#define BUTTERFLY_KEY_KP_4 324
#define BUTTERFLY_KEY_KP_5 325
#define BUTTERFLY_KEY_KP_6 326
#define BUTTERFLY_KEY_KP_7 327
#define BUTTERFLY_KEY_KP_8 328
#define BUTTERFLY_KEY_KP_9 329
#define BUTTERFLY_KEY_KP_DECIMAL 330
#define BUTTERFLY_KEY_KP_DIVIDE 331
#define BUTTERFLY_KEY_KP_MULTIPLY 332
#define BUTTERFLY_KEY_KP_SUBTRACT 333
#define BUTTERFLY_KEY_KP_ADD 334
#define BUTTERFLY_KEY_KP_ENTER 335
#define BUTTERFLY_KEY_KP_EQUAL 336
#define BUTTERFLY_KEY_LEFT_SHIFT 340
#define BUTTERFLY_KEY_LEFT_CONTROL 341
#define BUTTERFLY_KEY_LEFT_ALT 342
#define BUTTERFLY_KEY_LEFT_SUPER 343
#define BUTTERFLY_KEY_RIGHT_SHIFT 344
#define BUTTERFLY_KEY_RIGHT_CONTROL 345
#define BUTTERFLY_KEY_RIGHT_ALT 346
#define BUTTERFLY_KEY_RIGHT_SUPER 347
#define BUTTERFLY_KEY_MENU 348
