#pragma once

// From glfw3.h
#define BUTTERFLY_MOUSE_BUTTON_1 0
#define BUTTERFLY_MOUSE_BUTTON_2 1
#define BUTTERFLY_MOUSE_BUTTON_3 2
#define BUTTERFLY_MOUSE_BUTTON_4 3
#define BUTTERFLY_MOUSE_BUTTON_5 4
#define BUTTERFLY_MOUSE_BUTTON_6 5
#define BUTTERFLY_MOUSE_BUTTON_7 6
#define BUTTERFLY_MOUSE_BUTTON_8 7
#define BUTTERFLY_MOUSE_BUTTON_LAST BUTTERFLY_MOUSE_BUTTON_8
#define BUTTERFLY_MOUSE_BUTTON_LEFT BUTTERFLY_MOUSE_BUTTON_1
#define BUTTERFLY_MOUSE_BUTTON_RIGHT BUTTERFLY_MOUSE_BUTTON_2
#define BUTTERFLY_MOUSE_BUTTON_MIDDLE BUTTERFLY_MOUSE_BUTTON_3
